### PR TITLE
Enhancement: support displaying summary report per suite in SeleniumTestReport.html

### PR DESCRIPTION
**Pull request by malcolmshen**
I have multiple test suites and in each test suite there are many tests.  In the summary report, all tests are mixed in the same section and the title of the summary report is using the name of the first xml suite. So I enhanced the report generation part.  The "summaryPerSuite" report may be like this if there are multiple test suites:
testreport

### CODE REVIEW

**Comment by TestingForum** [comment]
How about displaying all suite summary together to have an instant overview of test result, that is - 

Suite_TestSuite1
 Tests in Test Suite
   Test2
Suite_TestSUite2
 Tests in Test Suite
   Test1
Suite_TestSUite_N
 Tests in Test Suite
   Test_1

Doing so one does not have to scroll down to get the overall summary

And then default display of Test2 > When user clicks on Test1 then Test1 details are displayed

What do you think?

**Comment by malcolmshen** [comment]
yes, i've also considered this solution, I did the above changes since it requires less code change and has less impacts.  I agree with you that it would be better to do it that way.  Kinda busy these days, let me grab some time and make it better.

**Comment by malcolmshen** [comment]
I checked the code.  It's an easy change.  I also modified two template files.  Make the report detail section hidden from the source code level instead of using javascripts to toggle them in client side.  And also fixed a js issue.  "$('div#reports').children().hide();" this line actually can be removed since it's hidden when page loading.

**Comment by TestingForum** [comment]
worked perfect, merged :)

**Pull request merged**
