### PR TITLE
Fix js errors in seleniumTestReport.html

### PR DESCRIPTION
**Pull request by malcolmshen**
a successive code change after this [pull request](https://github.com/TestingForum/seleniumtestsframework/pull/4)

### CODE REVIEW

**Comment by TestingForum** [comment]
I applied the changed manually instead of resolving conflict since it was one line change ;-)
You could try new version - 

`<groupId>com.seleniumtests</groupId>`
`<artifactId>seleniumtestsframework</artifactId>`
`<version>4.0.2</version>`

**Comment by TestingForum** [comment]
@malcolmshen I applied the changed manually instead of resolving conflict since it was one line change ;-)
You could try new version -

`<groupId>com.seleniumtests</groupId>`
`<artifactId>seleniumtestsframework</artifactId>`
`<version>4.0.2</version>`

And thanks for pull request

**Comment by malcolmshen** [comment]
So efficient!  I'm glad to contribute. I may still have some other pull requests.  You may reject them if they are not good changes.

**Comment by malcolmshen** [comment]
Is there something wrong with the code merge?  I was creating another pull request and found the code change of last pull request is not applied.
_2016-04-01t02-49-53 444z

**Comment by TestingForum** [comment]
@malcolmshen my bad. Please check new version 4.0.3
Keep the pull requests coming :)

**Comment by malcolmshen** [comment]
The new version 4.0.3 is okay.

**Comment by malcolmshen** [comment]
However the master is still 4.0.2 in pom.xml and the [SeleniumTestsReporter.java](https://github.com/TestingForum/seleniumtestsframework/blob/master/src/main/java/com/seleniumtests/reporter/SeleniumTestsReporter.java) is still not correctly merged.  

This line
`context.put("testId", name.toLowerCase().replace(' ', '_').replace('(', '_').replace(')', '_'));`

should be
`context.put("testId", StringUtility.md5(name));`

**Comment by TestingForum** [comment]
Master is also on 4.0.3
I guess every thing is set now

**Comment by malcolmshen** [comment]
yes, all set now.

**Comment by malcolmshen** [comment]
Still [one line code change](https://github.com/TestingForum/seleniumtestsframework/pull/4/commits/609259de6b81324d089b8d0b524d632bd35b6fa5) is missed:

_2016-04-05t04-26-31 790z

**Comment by TestingForum** [comment]
Updated and released version 4.0.4
I should not have merged the first pull request without testing. Lesson to self :-)
Please test and let me know if you find any more issue.

**Comment by malcolmshen** [comment]
yes, i also learned from it.  I tested every code change in both the original code base and my own project after the first pull request.

**Pull request closed without merging**
